version: "3.8"

services:
  gerenciamento:
    build: ./gerenciamento
    container_name: gerenciamento
    ports:
      - "5000:5000"
    volumes:
      - ./gerenciamento:/app
    environment:
      - FLASK_ENV=development

  reservas:
    build: ./reservas
    container_name: reservas
    ports:
      - "5001:5000"   
    depends_on:
      - gerenciamento
    environment:
      - GERENCIAMENTO_URL=http://gerenciamento:5000
    volumes:
      - ./reservas:/app

  atividades:
    build: ./atividades
    container_name: atividades
    ports:
      - "5002:5000"   
    depends_on:
      - gerenciamento
    environment:
      - GERENCIAMENTO_URL=http://gerenciamento:5000
    volumes:
      - ./atividades:/app
